export const styles = (darkMode) => ({
  container: {
    backgroundColor: darkMode ? "#121212" : "#ffffff",
    color: darkMode ? "#f1f1f1" : "#000000",
    padding: "1rem",
    fontFamily: "Segoe UI, sans-serif",
    width: "100%",
    maxWidth: "1000px",
    margin: "auto",
    minHeight: "100vh",
    boxSizing: "border-box",
  },
  section: {
    marginTop: "2rem",
    padding: "1rem",
    backgroundColor: darkMode ? "#1e1e1e" : "#ffffff",
    border: `1px solid ${darkMode ? "#333" : "#ddd"}`,
    borderRadius: "12px",
    boxShadow: darkMode
      ? "0 4px 12px rgba(0,0,0,0.4)"
      : "0 4px 12px rgba(0,0,0,0.08)",
    overflowX: "auto",
  },
  item: {
    padding: "1rem",
    marginBottom: "1rem",
    background: darkMode ? "#2a2a2a" : "#f9fafc",
    borderRadius: "8px",
    border: `1px solid ${darkMode ? "#444" : "#d1d5db"}`,
    fontSize: "0.95rem",
  },
  button: {
    padding: "0.6rem 1.2rem",
    margin: "0.25rem",
    border: "none",
    borderRadius: "8px",
    backgroundColor: "#2563eb",
    color: "white",
    fontWeight: "bold",
    cursor: "pointer",
    fontSize: "0.95rem",
    width: "100%",
    maxWidth: "220px",
    textAlign: "center",
  },
  select: {
    padding: "0.5rem",
    margin: "0.25rem",
    borderRadius: "6px",
    border: `1px solid ${darkMode ? "#666" : "#ccc"}`,
    background: darkMode ? "#1e1e1e" : "#fff",
    color: darkMode ? "#f1f1f1" : "#000",
    fontSize: "0.95rem",
    width: "100%",
    maxWidth: "220px",
  },
  toggleWrapper: {
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  toggleTrack: {
    width: "50px",
    height: "26px",
    backgroundColor: "#6b7280",
    borderRadius: "999px",
    position: "relative",
    transition: "background-color 0.3s ease",
    flexShrink: 0,
  },
  toggleThumb: (darkMode) => ({
    width: "22px",
    height: "22px",
    backgroundColor: "#fff",
    borderRadius: "50%",
    position: "absolute",
    top: "2px",
    left: darkMode ? "26px" : "2px",
    transition: "left 0.25s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
    lineHeight: 1,
  }),
  controlRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "1rem",
    marginBottom: "1rem",
    justifyContent: "flex-start",
    alignItems: "center",
  },
});
